### ISSUE TITLE
os : windows/osx, python: "3.6" does not set $TRAVIS_PYTHON_VERSION

### ISSUE THREAD

**Issue by cclauss** [kangwonlee/travis-yml-conda-posix-nt#2]
__$TRAVIS_PYTHON_VERSION__ is only getting set on __os: linux__

**Comment by kangwonlee** [comment]
* To my best understanding so far, as you pointed out, Travis-CI seems to support python only on `linux`.
* I plan to make following changes

* [x] `language : shell` 3ed8d6d94e2c8011abea0ae7d643da6cb48539aa
* [x] `env : CONDA_PYTHON=3.6` 3ed8d6d94e2c8011abea0ae7d643da6cb48539aa
* [x] `echo : $CONDA_PTYHON` c2c7f45eb43675fa022eeca788378c6cb33869ff

**Comment by cclauss** [comment]
https://github.com/cclauss/Travis-CI-Python-on-three-OSes/blob/master/conda_on_Windows.yml seems to work.  Redefining __$PATH__ is also key.

**Comment by kangwonlee** [comment]
* [x] Revise path 2e9f79391d123fe47b3e02b3e929fb2b5466b2d8
* [x] Run `profile.d/conda.sh` 7e860197ffe24fe1ef4d4561e4a6d1dbe3cb62f2
* [x] Add `openssl` otherwise `conda` cannot update 7f1fa3a9dd6435009534d7b15b79e7cb36ad71aa

**Comment by kangwonlee** [comment]
* IMHO 68256641a62179f517c37eb2c2a41ee64de714e8 resolves this issue
* 9100690dcb80db69d26d75a9c2921a6db71f9e77 [verifies](https://travis-ci.org/kangwonlee/travis-yml-conda-posix-nt/builds/516494378) with multiple versions of python
