### ISSUE TITLE
Turn on the Travis testing for this repo?

### ISSUE THREAD

**Issue by cclauss** [kangwonlee/travis-yml-conda-posix-nt#5]
https://travis-ci.org/kangwonlee/travis-yml-conda-posix-nt

**Comment by kangwonlee** [comment]
* Thanks for the suggestion
* I agree about the need; otherwise, it would be like an open loop
* I am thinking about adding a couple of [sample recipes](https://github.com/kangwonlee/nmisp/tree/develop/tests) (or [more like these](https://github.com/kangwonlee/test_ipynb)?)

**Comment by kangwonlee** [comment]
* IMHO 9100690dcb80db69d26d75a9c2921a6db71f9e77 resolves this issue
